name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies
        run: sudo apt install libfmt-dev

      - name: Build
        run: ninja

      - name: Run
        run: |
          build/1
