name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        run: ninja

      - name: Run a multi-line script
        run: |
          build/1
